### ISSUE TITLE
Call to a member function render() on a non-object

### ISSUE THREAD

**Issue by goosechaser** [rcrowe/Turbo#1]
Hi,

I get an error after adding `Turbo\Provider\Laravel\TurboServiceProvider` to the list of providers.

```
Symfony\Component\Debug\Exception\FatalErrorException
…\vendor\rcrowe\turbo\src\Turbo\Provider\Laravel\TurboServiceProvider.php31

            $turbo = new Turbo($response->getOriginalContent()->render());
```

**Comment by rcrowe** [comment]
$response->getOriginalContent() returns a string not a view object within the event.

The reason Turbo does this is that is has to render the view in order to extract the `<body>` and `<title>`, so by the time the event has fired the view has already been rendered.

I'm not sure why you are creating an instance of `Turbo` and trying to pass in a parameter. Looks like maybe your using an older version of the Library, `0.2.0` is the latest version.

``` php
Event::listen('turbo.pjax', function($request, $response) {
    var_dump( $response->getOriginalContent() );
});
```

This will give you the HTML that is to be returned to the client as a string.

**Comment by goosechaser** [comment]
I was using `"rcrowe/turbo": "0.1.*"` as per your installation instructions. Perhaps you should change them :) Thanks.

**Comment by goosechaser** [comment]
Still getting an error but this time ONLY when a `pjax` request is sent (e.g., `http://site.com/test?_pjax=%23ajax`). 

Screenshot: http://i.imgur.com/5mtV7Rh.png

**Comment by rcrowe** [comment]
Are you doing anything special with your views? Using any other packages that affect this?

I just haven't seen this before, so will have to help me debug it. If you output `get_class($response)` what class is it?

Is it possible to put make your codebase / example available.

**Comment by goosechaser** [comment]
- My template is an empty file with "test" string inside it.
- I am returning `View::make('template')`.
- Response class is `string(24) "Illuminate\Http\Response"`.
- PJAX works fine without TURBO. I have not issues with anything else. 
- My `routes.php` as `Event::listen` as per your usage/installation instructions.

**Comment by rcrowe** [comment]
Is the error taking place in the Event?

I have the same thing setup working fine, so not sure what's happening here.

I'll put an example of Turbo up later see if it helps you.

**Comment by goosechaser** [comment]
Nope, it's not the event that's causing it. It works if you remove the `->render()` method.

**Comment by rcrowe** [comment]
I'll put an example together and see whether it works fine for you. Can't repeat the issue you are seeing.

**Comment by goosechaser** [comment]
Try using your code with:

```
$template = View::make("template");
return $template;
```

**Comment by rcrowe** [comment]
Are you still seeing this issue? still not able to recreate it here.

**Comment by rcrowe** [comment]
Can you try changing your composer dependency to the following and see if it fixes your issue.

```
"rcrowe/turbo": "dev-render"
```
